- name: Set container provision dir
  set_fact:
    docker_provision_dir: '/tmp/contrail-container-deployer'

- name: Clone contrail-ansible-deployer repository
  git:
    repo: 'https://github.com/Juniper/contrail-ansible-deployer'
    version: 'a32639c61f4c5c20fddb99ccb25f75944cf2ca0a'
    force: yes
    dest: "{{ docker_provision_dir }}"

