- hosts: all
  roles:
    - role: tox
      tox_envlist: ical

  post_tasks:

    - name: Collect yaml2ical output
      synchronize:
        dest: "{{ zuul.executor.work_root }}/yaml2ical"
        mode: pull
        src: "src/{{ zuul.project.canonical_name }}/output"
        verify_host: true
