- hosts: all
  tasks:
    - debug:
        var: zuul
    - debug:
        var: hostvars
    - zuul_return:
        data:
          from_a_child_pre: a_child_pre_value
      delegate_to: localhost
    - zuul_return:
        data:
          zuul:
            zuul_from_a_child_pre: zuul_a_child_pre_value
      delegate_to: localhost
