- hosts: all
  pre_tasks:
    - name: check for package repo existence
      uri:
        url: http://10.84.5.81/pulp/repos/38333-2/
      ignore_errors: yes
      register: package_repo
    - name: Playbook exiting with SUCCESS because the packages are already built
      debug:
        msg: '0'
      when: package_repo.status == 200
    - name: exit if repo exists
      meta: end_play
      when: package_repo.status == 200
  roles:
    - zuulv3-self-test
  tasks:
    - name: async
      pause:
        minutes: 1
      async: 180
      poll: 10
      with_items:
        - pause1
        - pause2
        - pause3
        - pause4

- hosts: all
  tasks:
    - name: debug1
      debug:
        msg: 123
