- hosts: all
  pre_tasks:
    - name: check for package repo existence
      uri:
        url: http://10.84.5.81/pulp/repos/38333-5/
      ignore_errors: yes
      register: package_repo
    - name: exit if repo exists
      meta: end_play
      when: package_repo.status == 200
  roles:
    - zuulv3-self-test
