- hosts: all
  roles:
    - contrail-common-libs
    - packaging-prepare-contrail-el
    - packaging-build-el
    - packaging-upload-el

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  vars:
    reponame: "{{ zuul.change }}-{{ zuul.patchset }}"
    executor_package_dir: "{{ zuul.executor.work_root }}/packages"
  roles:
    - packaging-publish-el

- hosts: builder
  roles:
    - contrail-build-dockers
