- name: Set container build dir
  set_fact:
    docker_build_dir: '/tmp/contrail-container-builder'

- name: Clone contrail-container-builder repository
  git:
    repo: 'https://github.com/Juniper/contrail-container-builder'
    version: 'def20a6a0ec648edbc6f6c11a43629767312f123'
    force: yes
    dest: "{{ docker_build_dir }}"

- name: Prepare container build configuration
  command: cp common.env.sample common.env
  args:
    chdir: "{{ docker_build_dir }}"

- name: Prepare container build environment
  command: bash setup-for-build.sh
  become: true
  args:
    chdir: "{{ docker_build_dir }}/containers"

- name: Build containers
  command: "{{ docker_build_dir }}/containers/build.sh"
  become: true
  args:
    chdir: "{{ docker_build_dir }}/containers"

- name: Get a list of logs
  find:
    paths: "{{ docker_build_dir }}"
    patterns: '*contrail-container-builder*.log'
  register: loglist

- name: Gzip the log files
  archive:
    path: "{{ item.path }}"
    remove: true
  with_items: "{{ loglist.files }}"

- name: Send logs to the executor
  synchronize:
    mode: pull
    src: "{{ item.path }}.gz"
    dest: "{{ zuul.executor.log_root }}/docker"
  with_items: "{{ loglist.files }}"
