- name: Set container build dir
  set_fact:
    docker_build_dir: '/tmp/contrail-container-builder'

- name: Clone contrail-container-builder repository
  git:
    repo: 'https://github.com/Juniper/contrail-container-builder'
    version: '06ae9610f1b481eaca4fcfa3ce40a87bf3f98e82'
    force: yes
    dest: "{{ docker_build_dir }}"

- name: Prepare container build configuration
  command: cp common.env.sample common.env
  args:
    chdir: "{{ docker_build_dir }}"

- name: Prepare container build configuration registry
  shell: "echo '_CONTRAIL_REGISTRY_IP=10.84.56.38' >> common.env"
  args:
    chdir: "{{ docker_build_dir }}"

- name: Prepare container build environment
  command: bash setup-for-build.sh
  become: true
  args:
    chdir: "{{ docker_build_dir }}/containers"

- name: Build containers
  command: "{{ docker_build_dir }}/containers/build.sh"
  become: true
  args:
    chdir: "{{ docker_build_dir }}/containers"

- name: Get a list of logs
  find:
    paths: "{{ docker_build_dir }}/containers"
    patterns: '*contrail-container-builder*.log'
  register: loglist

- name: Gzip the log files
  archive:
    path: "{{ item.path }}"
    remove: true
  with_items: "{{ loglist.files }}"

- name: Send logs to the executor
  synchronize:
    mode: pull
    src: "{{ item.path }}.gz"
    dest: "{{ zuul.executor.log_root }}/docker/"
  with_items: "{{ loglist.files }}"
