# when using docker, we need a number of directories
# to bind mount between host and the container:
#   - tmp/ where all source code is stored -- required
#       so that the build does not suffer from the aufs
#       performance penatly.
#   - packages/ where the resulting packages will be stored.
- name: Create working directory structure
  file: dest="{{ item }}" state=directory
  with_items:
    - tmp
    - tmp/tools
    - packages

- name: Debug zuul variable
  debug: var=zuul

- name: Hard-link repositories into expected structure
  synchronize: |
    src="{{ ansible_env.HOME }}/src/review2.opencontrail.org/Juniper/{{ item.src }}"
    dest="{{ ansible_env.HOME }}/tmp/{{ item.dest }}"
  with_items:
    - { src: 'contrail-controller/', dest: 'controller' }
    - { src: 'contrail-build/', dest: 'tools/build' }
    - { src: 'contrail-generateDS/', dest: 'tools/generateds' }
    - { src: 'contrail-sandesh/', dest: 'tools/sandesh' }
    - { src: 'contrail-third-party/', dest: 'third_party' }
    - { src: 'contrail-vrouter/', dest: 'vrouter' }
    - { src: 'contrail-build/SConstruct', dest: '' }
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Copy debian/ to enable package building
  synchronize: |
    src="{{ ansible_env.HOME}}/src/review2.opencontrail.org/Juniper/contrail-packages/debian/contrail/debian"
    dest="{{ ansible_env.HOME }}/tmp/"
    rsync_opts="--no-motd,--exclude=.git,--quiet"
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Pull the latest Ubuntu 16.04 docker image from the registry
  docker_image: |
    name=1.1.1.41:5000/contrail-builder:5.0-xenial

- name: Start the builder container
  docker_container:
    name: "builder"
    state: "started"
    recreate: true
    image: "1.1.1.41:5000/contrail-builder:5.0-xenial"
    command: "sleep infinity"
    volumes:
      - "{{ ansible_env.HOME }}/packages:/build"
      - "{{ ansible_env.HOME }}/tmp:/build/contrail"
  register: builder

- name: Debug builder variable
  debug: var=builder

- name: Debug zuul variable
  debug: var=zuul

- name: Debug job variable
  debug: var=job

- name: Define contrail version
  shell: |
    echo -n 4.0-1~34341.1.$(date +%Y%m%d.%H%m%S)
  register: version

- name: Update debian/changelog
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && builder dch -v {{ version.stdout }} -m ""'
    docker exec -t builder sh -c 'cd /build/contrail/ && dch --release --distribution xenial -m "Releasing version {{ version.stdout }}."'

- name: Create orig tarball
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && fakeroot debian/rules get-orig-source'
    mv {{ ansible_env.HOME }}/tmp/contrail_{{ version.stdout }}.orig.tar.gz {{ ansible_env.HOME }}/packages/

- name: Create contrail source package
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && debuild -S -us -uc'
