# when using docker, we need a number of directories
# to bind mount between host and the container:
#   - tmp/ where all source code is stored -- required
#       so that the build does not suffer from the aufs
#       performance penatly.
#   - packages/ where the resulting packages will be stored.
- name: Create working directory structure
  file: dest="{{ item }}" state=directory
  with_items:
    - tmp
    - packages

- name: Debug zuul variable
  debug: var=zuul

- name: Hard-link repositories into expected structure
  synchronize: |
    src="{{ ansible_env.HOME }}/src/review2.opencontrail.org/Juniper/{{ item.src }}"
    dest="{{ ansible_env.HOME }}/tmp/{{ item.dest }}"
  with_items:
    - { src: 'contrail-controller', dest: 'controller' }
    - { src: 'contrail-build', dest: 'controller' }
    - { src: 'contrail-generateDS', dest: 'tools/generateDS' }
    - { src: 'contrail-sandesh', dest: 'tools/sandesh' }
    - { src: 'contrail-third-party', dest: 'third-party' }
    - { src: 'contrail-vrouter', dest: 'vrouter' }
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Copy debian/ to enable package building
  synchronize: |
    src="src/review2.opencontrail.org/Juniper/contrail-packages/debian/contrail/debian/"
    dest="tmp/debian/"
