# when using docker, we need a number of directories
# to bind mount between host and the container:
#   - tmp/ where all source code is stored -- required
#       so that the build does not suffer from the aufs
#       performance penatly.
#   - packages/ where the resulting packages will be stored.
- name: Create working directory structure
  file: dest="{{ item }}" state=directory
  with_items:
    - tmp
    - tmp/tools
    - tmp/openstack
    - packages

- name: Debug zuul variable
  debug: var=zuul

- name: Hard-link repositories into expected structure
  synchronize: |
    src="{{ ansible_env.HOME }}/src/review2.opencontrail.org/Juniper/{{ item.src }}"
    dest="{{ ansible_env.HOME }}/tmp/{{ item.dest }}"
  with_items:
    - { src: 'contrail-controller/', dest: 'controller' }
    - { src: 'contrail-build/', dest: 'tools/build' }
    - { src: 'contrail-generateDS/', dest: 'tools/generateds' }
    - { src: 'contrail-sandesh/', dest: 'tools/sandesh' }
    - { src: 'contrail-third-party/', dest: 'third_party' }
    - { src: 'contrail-vrouter/', dest: 'vrouter' }
    - { src: 'contrail-build/SConstruct', dest: '' }
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Copy debian/ to enable package building
  synchronize: |
    src="{{ ansible_env.HOME}}/src/review2.opencontrail.org/Juniper/contrail-packages/debian/contrail/debian"
    dest="{{ ansible_env.HOME }}/tmp/"
    rsync_opts="--no-motd,--exclude=.git,--quiet"
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Pull the latest Ubuntu 16.04 docker image from the registry
  docker_image: |
    name=1.1.1.41:5000/contrail-builder:5.0-xenial

- name: Start the builder container
  docker_container:
    name: "builder"
    state: "started"
    recreate: true
    image: "1.1.1.41:5000/contrail-builder:5.0-xenial"
    command: "sleep infinity"
    env:
      USER: builder
    user: 1002:1002
    volumes:
      - "{{ ansible_env.HOME }}/packages:/build"
      - "{{ ansible_env.HOME }}/tmp:/build/contrail"
  register: builder

- name: Debug builder variable
  debug: var=builder

- name: Debug zuul variable
  debug: var=zuul

- name: Debug job variable
  debug: var=job

- name: Define contrail version
  set_fact:
    version:
      upstream: "{% if zuul.branch == 'master' %}{{ contrail_default_version }}{% else %}{{ zuul.branch }}{% endif %}"
      packaging: "{{ zuul.change }}.{{ zuul.patchset }}"
      date: >-
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}
      date_2: |
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}
      date_3: >
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}
      date_4: >+
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}
      date_5: |-
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}
      date_6: |+
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}

- name: Update debian/changelog
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && dch -v {{ version.upstream }}-1~{{version.packaging}}.{{ version.date }} -m ""'
    docker exec -t builder sh -c 'cd /build/contrail/ && dch --release --distribution xenial -m "Releasing version {{ version.upstream }}-1~{{version.packaging}}.{{ version.date }}."'

- name: Create orig tarball
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && fakeroot debian/rules get-orig-source'
    mv {{ ansible_env.HOME }}/tmp/contrail_{{ version.upstream }}.orig.tar.gz {{ ansible_env.HOME }}/packages/

- name: Create contrail source package
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && debuild -S -us -uc'
