- name: Populate ansible variables with packaging info
  prepare_packaging_vars:
    packaging_repo: "{{ zuul.project }}"
    distribution: "{{ ansible_distribution|lower() }}"
    release: "{{ ansible_distribution_release }}"
  register: package

- name: Copy upstream repository into the workdir
  synchronize:
    src: "{{ ansible_env.HOME}}/{{ package.upstream.source_dir }}"
    dest: "{{ ansible_env.HOME}}/{{ package.upstream.target_path }}"
    rsync_opts:
      - --quiet
      - --exclude='.git/'
  when: package.upstream is defined
  delegate_to: "{{ ansible_default_ipv4.address }}"
