- name: Populate ansible variables with packaging info
  prepare_packaging_vars:
    packaging_repo: "{{ zuul.project }}"
    distribution: "{{ ansible_distribution }}"
    release: "{{ ansible_distribution_release }}"