- name: Get a list of all files and directories in the workspace
  command: ls -1 {{ ansible_env.HOME }}
  register: files

- name: Clean-up the workspace
  file:
    path: "{{ item }}"
    state: absent
  when: item != "src"
  with_items: "{{ files.stdout_lines }}"

- name: Populate ansible variables with packaging info
  prepare_packaging_vars:
    packaging_repo: "{{ zuul.project }}"
    distribution: "{{ ansible_distribution|lower() }}"
    release: "{{ ansible_distribution_release }}"
  register: package

- name: Copy upstream repository into the workdir
  synchronize:
    src: "{{ ansible_env.HOME}}/{{ package.upstream.source_dir }}"
    dest: "{{ ansible_env.HOME}}/{{ package.upstream.target_path }}"
    rsync_opts:
      - --quiet
      - --exclude='.git/'
  when: package.upstream is defined
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Create an orig tar.gz with upstream sources
  archive:
    path:
      - "{{ package.upstream.target_path }}"
    dest: "{{ package.package.name }}-{{ package.package.version.upstream }}.orig.tar.gz"

- name: Copy packaging from the packaging repo
  synchronize:
    src: "{{ ansible_env.HOME}}/{{ package.package.debian_dir }}"
    dest: "{{ ansible_env.HOME}}/{{ package.upstream.target_path }}/debian/"
    rsync_opts:
      - --quiet
      - --exclude='.git/'
  when: package.upstream is defined
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Fetch a generic ubuntu docker image for build
  docker_image:
    name: "ubuntu:{{ ansible_distribution_release }}"

- name: Launch a build container
  docker_container:
    name: "builder"
    state: "started"
    recreate: true
    image: "ubuntu:{{ ansible_distribution_release }}"
    command: "sleep infinity"
    env:
      USER: builder
      DEB_BUILD_OPTIONS: "parallel={{ ansible_processor_vcpus }}"
    user: "{{ ansible_effective_user_id }}:{{ ansible_effective_group_id }}"
    volumes:
      - "{{ ansible_env.HOME }}:/build"

- name: Add Ubuntu Cloud archive for the given OpenStack release
  shell: |
    docker exec --user root:root builder sh -c '
      apt-get update
      apt-get install --assume-yes ubuntu-cloud-keyring
      echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/ocata main" \
        >> /etc/apt/sources.list'

- name: Install build-related packages in the container
  shell: |
    docker exec --user root:root builder sh -c '
      apt-get update
      apt-get install --no-install-recommends --assume-yes \
        devscripts equivs build-essential'

- name: Install package dependencies for the build
  shell: |
    docker exec --user root:root builder sh -c '
      cd /build/{{ package.upstream.target_path }}/
            mk-build-deps -i -r debian/control \
        --tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes"
      apt-get autoremove --assume-yes --purge'

- name: Create source and binary debian packages
  shell: |
    docker exec builder sh -c '
      cd /build/{{ package.upstream.target_path }}/
      debuild -us -uc'