- name: Populate ansible variables with packaging info
  prepare_packaging_vars:
    packaging_repo: "{{ zuul.project }}"
    distribution: "{{ ansible_distribution|lower() }}"
    release: "{{ ansible_distribution_release }}"
  register: package

