- name: Populate ansible variables with packaging info
  prepare_packaging_vars:
    packaging_repo: {{ zuul.project.short_name }}
    source_repo: {{ packaging_source_repository }}
    distribution: {{ ansible_distribution }}
    release: {{ ansible_distribution_release }}