- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - prepare-static-host
    - add-build-sshkey
    - start-zuul-console
    - validate-host
    - mirror-workspace-git-repos
