- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
    - validate-host
    - cleanup-workspace
    - prepare-workspace
