- name: Update debian/changelog
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && dch -v {{ version.upstream }}-1~{{version.packaging}}.{{ version_date }} -m ""'
    docker exec -t builder sh -c 'cd /build/contrail/ && dch --release --distribution xenial -m "Releasing version {{ version.upstream }}-1~{{version.packaging}}.{{ version_date }}."'

- name: Create orig tarball
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && fakeroot debian/rules get-orig-source'
    mv {{ ansible_env.HOME }}/tmp/contrail_{{ version.upstream }}.orig.tar.gz {{ ansible_env.HOME }}/packages/

- name: Create contrail source package
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && debuild -S -us -uc'

- name: Create contrail binary packages
  shell: |
    docker exec -t builder sh -c 'cd /build/contrail/ && debuild -i -us -uc'
