- name: add packages to repo
  uri:
    url: http://1.1.1.59/api/repos/{{ reponame }}/file/{{ reponame }}
    method: POST
    user: aptly
    password: aptlypassword
    force_basic_auth: yes
    status_code: 201
- name: publish repo
  uri:
    url: http://1.1.1.59/api/publish
    method: POST
    user: aptly
    password: aptlypassword
    body: '{ "SourceKind": "local", "Sources": [{"Name": "{{ reponame }}"}], "Architectures": ["amd64"] }'
    force_basic_auth: yes
    body_format: json
    status_code: 201
