- name: create destination directory
  file:
    state: directory
    path: /var/lib/aptly/upload/{{ reponame }}/

- name: upload packages to aptly
  synchronize:
    src: "{{ zuul.executor.work_root }}/debs/"
    dest: /var/lib/aptly/upload/{{ reponame }}
