- name: create destination directory
  file:
    state: directory
    path: /var/lib/aptly/upload/{{ reponame }}/

- name: upload packages to aptly
  synchronize:
    src: "{{ src_dir }}/*.deb"
    dest: /var/lib/aptly/upload/{{ reponame }}/
    mode: pull
