- hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "src/{{ zuul.project.canonical_name }}"
    - legacy-install-afs-with-puppet
    - legacy-copy-project-config-scripts
