# when using docker, we need a number of directories
# to bind mount between host and the container:
#   - tmp/ where all source code is stored -- required
#       so that the build does not suffer from the aufs
#       performance penatly.
#   - packages/ where the resulting packages will be stored.
- name: Create working directory structure
  file: dest="{{ item }}" state=directory
  with_items:
    - tmp
    - tmp/tools
    - tmp/openstack
    - packages

- name: Hard-link gerrit repositories into expected structure
  synchronize: |
    src="{{ ansible_env.HOME }}/src/review2.opencontrail.org/Juniper/{{ item.src }}"
    dest="{{ ansible_env.HOME }}/tmp/{{ item.dest }}"
  with_items:
    - { src: 'contrail-controller/', dest: 'controller' }
    - { src: 'contrail-build/', dest: 'tools/build' }
    - { src: 'contrail-generateDS/', dest: 'tools/generateds' }
    - { src: 'contrail-sandesh/', dest: 'tools/sandesh' }
    - { src: 'contrail-third-party/', dest: 'third_party' }
    - { src: 'contrail-vrouter/', dest: 'vrouter' }
    - { src: 'contrail-packages/', dest: 'tools/packages' }
    - { src: 'contrail-nova-vif-driver/', dest: 'openstack/nova_contrail_vif' }
    - { src: 'contrail-build/SConstruct', dest: '' }
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Hard-link github repositories into expected structure
  synchronize: |
    src="{{ ansible_env.HOME }}/src/github.com/Juniper/{{ item.src }}"
    dest="{{ ansible_env.HOME }}/tmp/{{ item.dest }}"
  with_items:
    - { src: 'contrail-nova-extensions/', dest: 'openstack/nova_extensions' }
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Copy debian/ to enable package building
  synchronize: |
    src="{{ ansible_env.HOME}}/src/review2.opencontrail.org/Juniper/contrail-packages/debian/contrail/debian"
    dest="{{ ansible_env.HOME }}/tmp/"
    rsync_opts="--no-motd,--exclude=.git,--quiet"
  delegate_to: "{{ ansible_default_ipv4.address }}"

- name: Pull the latest Ubuntu 16.04 docker image from the registry
  docker_image: |
    name={{ docker_registry }}contrail-builder:5.0-xenial

- name: Define contrail version
  set_fact:
    version:
      upstream: "{% if zuul.branch == 'master' %}{{ contrail_default_version }}{% else %}{{ zuul.branch }}{% endif %}"
      packaging: "{{ zuul.change }}.{{ zuul.patchset }}"
      # FIXME: Use strfime filter instead of calling replace later once we upgrade ansible to 2.4+
      #date: "{{ '%Y%m%d%H%M%S' | strftime }}"
      date: |-
         {{ ansible_date_time.year }}{{ ansible_date_time.month }}
         {{ ansible_date_time.day }}{{ ansible_date_time.hour }}
         {{ ansible_date_time.minute }}

- name: Strip new lines from version.date
  set_fact:
    version_date: "{{ version.date | replace('\n', '') }}"

- name: Start the builder container
  docker_container:
    name: "builder"
    state: "started"
    recreate: true
    image: "{{ docker_registry }}/contrail-builder:{{ version.upstream }}-xenial"
    command: "sleep infinity"
    env:
      USER: builder
      DEB_BUILD_OPTIONS: "parallel={{ ansible_processor_vcpus }}"
    # FIXME: replace with host zuul user
    user: 1002:1002
    volumes:
      - "{{ ansible_env.HOME }}/packages:/build"
      - "{{ ansible_env.HOME }}/tmp:/build/contrail"
  register: builder

