- name: Change contrail-packages to custom repo
  shell: |
    git remote add kklimonda https://github.com/kklimonda/contrail-packages
    git fetch --all
    git reset --hard kklimonda/ubuntu-contrail-vnc-cleanup
  args:
    chdir: "{{ ansible_env.HOME}}/contrail-5.0/tools/packages/"
