- hosts: all
  tasks:

    - name: Run propose_update.sh script
      command: "{{ ansible_user_dir }}/scripts/propose_update.sh {{ update_target }}"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}"
