- hosts: all
  tasks:
    - name: set variables
      set_fact:
        executor_package_dir: "{{ zuul.executor.work_root }}/packages"
        worker_package_dir: "{{ ansible_env.HOME }}/rpmbuild"
    - name: create package dir on the executor
      file:
        path: "{{ executor_package_dir }}"
        state: directory
      delegate_to: localhost

- hosts: all
  tasks:
    - name: set variables
      set_fact:
        executor_package_dir: "{{ zuul.executor.work_root }}/packages"
        worker_package_dir: "{{ ansible_env.HOME }}/rpmbuild"
    - name: create package dir on the worker
      file:
        path: "{{ worker_package_dir }}"
        state: directory
    - name: get some packages
      get_url:
        url: "{{ item }}"
        dest: "{{ worker_package_dir }}"
      with_items:
        - http://mirror.centos.org/centos/7.4.1708/updates/x86_64/Packages/bind-license-9.9.4-51.el7.noarch.rpm
        - http://mirror.centos.org/centos/7.4.1708/updates/x86_64/Packages/augeas-1.4.0-2.el7_4.1.x86_64.rpm
    - name: send packages to the executor
      synchronize:
        src: "{{ worker_package_dir }}/*.rpm"
        dest: "{{ executor_package_dir }}"
        mode: pull

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  vars:
    reponame: "{{ zuul.change }}-{{ zuul.patchset }}"
    src_dir: "{{ worker_package_dir }}"
    executor_package_dir: "{{ zuul.executor.work_root }}/packages"
    worker_package_dir: "{{ ansible_env.HOME }}/rpmbuild"
  tasks:
    #- name: create destination directory
    #  file:
    #    state: directory
    #    path: /home/zuul/{{ reponame }}
    - name: upload packages to aptly
      synchronize:
        src: "{{ executor_package_dir }}"
        dest: /home/zuul/{{ reponame }}
    - name: delete repo
      command: pulp-admin -u {{ site_pulp.pulp_user }} -p {{ site_pulp.pulp_password }} rpm repo delete --repo-id {{ reponame }}
    - name: create repo
      command: pulp-admin -u {{ site_pulp.pulp_user }} -p {{ site_pulp.pulp_password }} rpm repo create --repo-id {{ reponame }}
    - name: add packages to pulp
      command: pulp-admin -u {{ site_pulp.pulp_user }} -p {{ site_pulp.pulp_password }} rpm repo uploads rpm --repo-id {{ reponame }} --dir /home/zuul/{{ reponame }}/packages
    - name: publish repo
      command: pulp-admin -u {{ site_pulp.pulp_user }} -p {{ site_pulp.pulp_password }} rpm repo publish run --repo-id {{ reponame }}
    - name: remove package directory from pulp server
      file:
        path: /home/zuul/{{ reponame }}
        state: absent
