- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_deb }}"

- hosts: ubuntu-xenial
  vars:
    reponame: "{{ zuul.build }}"
    src_dir: "./debs"
  roles:
    - prepare-debs

- hosts: "{{ site_deb.fqdn }}"
  vars:
    reponame: "{{ zuul.build }}"
    src_dir: "./debs"
  roles:
    - upload-debs

- hosts: ubuntu-xenial
  vars:
    reponame: "{{ zuul.build }}"
  roles:
    - publish-debs
